server:
  port: 8084

spring:
  application:
    name: fms-complaint-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fms_db
    username: fms_user
    password: fms_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
